using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace FEasyCreate.Editor
{
    /// <summary>
    /// Meng-generate file C# berisi item menu "Assets/Create/Easy Create/[Preset]" — satu per preset.
    /// Perlu code-gen karena MenuItem Unity harus statis (nama tak bisa dinamis saat runtime).
    /// File ditulis di PROJECT (Assets/Editor/FEasyCreate) karena nama preset spesifik-project.
    /// </summary>
    public static class FEasyCreateMenuGen
    {
        public const string GenPath = "Assets/Editor/FEasyCreate/FEasyCreateMenu.gen.cs";
        private const string MenuRoot = "Assets/Create/Easy Create/";

        /// <summary>Tulis ulang file menu dari daftar preset, lalu import supaya Unity meng-compile-nya.</summary>
        public static void Rebuild(FEasyCreateSettings settings)
        {
            if (settings == null) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Dibuat FEasyCreate — JANGAN diedit manual. </auto-generated>");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine();
            sb.AppendLine("namespace FEasyCreate.Editor.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class FEasyCreateMenuItems");
            sb.AppendLine("    {");

            int i = 0;
            foreach (var preset in settings.presets)
            {
                if (preset == null || string.IsNullOrWhiteSpace(preset.presetName)) continue;
                string menuPath = MenuRoot + EscapeMenu(preset.presetName);
                string nameLit = EscapeLiteral(preset.presetName);
                sb.AppendLine($"        [MenuItem(\"{EscapeLiteral(menuPath)}\", false, 80)]");
                sb.AppendLine($"        private static void _M{i}() => FEasyCreate.Editor.FEasyCreateRunner.Run(\"{nameLit}\");");
                i++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            FEasyCreateSettings.EnsureFolder("Assets/Editor/FEasyCreate");
            File.WriteAllText(GenPath, sb.ToString());
            AssetDatabase.ImportAsset(GenPath, ImportAssetOptions.ForceUpdate);
        }

        // Hindari '/' agar preset tak sengaja bikin submenu bertingkat; escape untuk string C#.
        private static string EscapeMenu(string s) => s.Replace('/', '⁄').Trim();
        private static string EscapeLiteral(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
